# Generated by Django 5.2.17 on 2026-08-18 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('source_url', models.URLField()),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('scheduled_date', models.DateField()),
                ('estimated_minutes', models.IntegerField(blank=True, null=True)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problems',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='student', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tag')),
            ],
            options={
                'db_table': 'problem_tags',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, through='tracker.ProblemTag', to='tracker.tag'),
        ),
        migrations.CreateModel(
            name='StudentProblemProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('started', 'Started'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('hidden', 'Hidden')], default='unassigned', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('share_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='tracker.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_progress', to='tracker.user')),
            ],
            options={
                'db_table': 'student_problem_progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems_created', to='tracker.user'),
        ),
        migrations.CreateModel(
            name='DailyActivitySummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('completed_count', models.IntegerField(default=0)),
                ('qualified_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='tracker.user')),
            ],
            options={
                'db_table': 'daily_activity_summary',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.AddIndex(
            model_name='problemtag',
            index=models.Index(fields=['problem', 'tag'], name='problem_tag_problem_6bf477_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='problemtag',
            unique_together={('problem', 'tag')},
        ),
        migrations.AddIndex(
            model_name='studentproblemprogress',
            index=models.Index(fields=['student', 'status'], name='student_pro_student_9e6228_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproblemprogress',
            index=models.Index(fields=['student', 'completed_at'], name='student_pro_student_874338_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproblemprogress',
            index=models.Index(fields=['problem', 'status'], name='student_pro_problem_8280a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentproblemprogress',
            unique_together={('student', 'problem')},
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['scheduled_date', 'publication_status'], name='problems_schedul_f87ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['created_by', 'publication_status'], name='problems_created_c96c81_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivitysummary',
            index=models.Index(fields=['student', 'activity_date'], name='daily_activ_student_5e3e80_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivitysummary',
            index=models.Index(fields=['activity_date'], name='daily_activ_activit_ad51aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivitysummary',
            unique_together={('student', 'activity_date')},
        ),
    ]
